"""GenBank (.gbk) writer for the final designed construct.

Produces a single GenBank record of the final circular plasmid annotated with:

  - ``primer_bind`` features for each primer (mapped onto the plasmid sequence
    by sequence search; the body is anchored, the tail is encoded as a note),
  - an ``insert`` ``misc_feature`` covering the cloned region,
  - an in-frame ``CDS`` where applicable (expression workflow → full coding
    sequence; tagging workflow → tag cassette ORF; deletion → scar ORF),
  - vector-derived ``misc_feature`` flagging the chosen restriction site.

The output is plain GenBank flat-file text — opens directly in SnapGene,
Benchling, ApE and BioPython without further processing.
"""
from __future__ import annotations

from datetime import date
from io import StringIO

from .types import (
    DeletionPrimerSet,
    DesignResult,
    ExpressionPrimerSet,
    Primer,
    TaggingPrimerSet,
)
from .vectors import find_all, reverse_complement


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def write_genbank(result: DesignResult) -> str:
    """Return a complete GenBank flat-file as a string."""
    plasmid_seq = result.final_plasmid.sequence.upper()
    length = len(plasmid_seq)

    buf = StringIO()
    _write_locus(buf, result, length)
    _write_definition(buf, result)
    _write_accession(buf, result)
    _write_keywords(buf, result)
    _write_source(buf)
    buf.write("FEATURES             Location/Qualifiers\n")
    _write_source_feature(buf, length)

    # Primers
    for p in _primers_in_order(result):
        _write_primer_feature(buf, p, plasmid_seq)

    # Insert / cassette / scar / CDS
    _write_application_features(buf, result, plasmid_seq)

    # Restriction site
    _write_enzyme_features(buf, result, plasmid_seq)

    # Origin
    _write_origin(buf, plasmid_seq)
    buf.write("//\n")
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Header blocks
# ---------------------------------------------------------------------------

def _locus_name(result: DesignResult) -> str:
    """≤ 16-char LOCUS name (GenBank convention)."""
    gene = result.gene_record.gene
    iso = result.gene_record.isolate_id
    app = {"deletion": "del", "tagging": "tag", "expression": "exp"}.get(
        result.request.application, result.request.application[:3]
    )
    name = f"{gene}_{iso}_{app}"
    return name[:16]


def _write_locus(buf: StringIO, result: DesignResult, length: int) -> None:
    today = date.today().strftime("%d-%b-%Y").upper()
    buf.write(
        f"LOCUS       {_locus_name(result):<16} {length:>11} bp    DNA     "
        f"circular SYN {today}\n"
    )


def _write_definition(buf: StringIO, result: DesignResult) -> None:
    gene = result.gene_record.gene
    iso = result.gene_record.isolate_id
    app = result.request.application
    vec = result.vector.name
    enz = result.request.enzyme
    buf.write(
        f"DEFINITION  {gene} {app} construct in {vec} ({iso}, {enz}). "
        f"Generated by AG Schwarz Primer Design.\n"
    )


def _write_accession(buf: StringIO, result: DesignResult) -> None:
    buf.write(f"ACCESSION   {_locus_name(result)}\n")
    buf.write("VERSION     .\n")


def _write_keywords(buf: StringIO, result: DesignResult) -> None:
    buf.write(
        f"KEYWORDS    primer design; {result.request.application}; "
        f"{result.gene_record.gene}; {result.vector.name}.\n"
    )


def _write_source(buf: StringIO) -> None:
    buf.write("SOURCE      synthetic DNA construct\n")
    buf.write("  ORGANISM  synthetic DNA construct\n")
    buf.write("            other sequences; artificial sequences.\n")


# ---------------------------------------------------------------------------
# Feature helpers
# ---------------------------------------------------------------------------

def _write_source_feature(buf: StringIO, length: int) -> None:
    buf.write(f"     source          1..{length}\n")
    buf.write('                     /organism="synthetic DNA construct"\n')
    buf.write('                     /mol_type="other DNA"\n')


def _write_feature(
    buf: StringIO,
    kind: str,
    start: int,
    end: int,
    qualifiers: list[tuple[str, str]],
    strand: str = "+",
) -> None:
    """Write a feature block. ``start``/``end`` are 1-based inclusive."""
    location = f"{start}..{end}" if strand == "+" else f"complement({start}..{end})"
    buf.write(f"     {kind:<16}{location}\n")
    for key, val in qualifiers:
        # Wrap long values at 58 chars (GenBank convention)
        text = f'/{key}="{val}"'
        for line in _wrap_qualifier(text):
            buf.write(f"                     {line}\n")


def _wrap_qualifier(text: str, width: int = 58) -> list[str]:
    if len(text) <= width:
        return [text]
    out = []
    while len(text) > width:
        out.append(text[:width])
        text = text[width:]
    if text:
        out.append(text)
    return out


# ---------------------------------------------------------------------------
# Primer features — locate body within the plasmid by sequence search
# ---------------------------------------------------------------------------

def _locate_primer(plasmid_seq: str, primer: Primer) -> tuple[int, int, str] | None:
    """Return (start_1based, end_1based, strand) for the primer body on the
    plasmid, or ``None`` if not found. Body is the template-binding 3' portion."""
    body = primer.body.upper()
    if not body:
        return None
    fwd = find_all(plasmid_seq, body)
    if fwd:
        s = fwd[0]
        return s + 1, s + len(body), "+"
    rev = find_all(plasmid_seq, reverse_complement(body))
    if rev:
        s = rev[0]
        return s + 1, s + len(body), "-"
    return None


def _write_primer_feature(buf: StringIO, primer: Primer, plasmid_seq: str) -> None:
    loc = _locate_primer(plasmid_seq, primer)
    qualifiers = [
        ("label", f"{primer.name} ({primer.role})"),
        ("note", (
            f"tail_kind={primer.tail_kind}; tail_len={len(primer.tail)}; "
            f"body_len={len(primer.body)}; Tm_body={primer.tm_body_C:.1f}C; "
            f"GC_body={int(primer.gc_body * 100)}%"
        )),
        ("note", f"sequence={primer.annotated_sequence}"),
    ]
    if loc is None:
        # Body did not match — still record the primer as an unanchored note.
        buf.write(f"     misc_feature    1..1\n")
        for key, val in qualifiers + [("note", "primer body not anchored on plasmid")]:
            for line in _wrap_qualifier(f'/{key}="{val}"'):
                buf.write(f"                     {line}\n")
        return
    start, end, strand = loc
    _write_feature(buf, "primer_bind", start, end, qualifiers, strand=strand)


# ---------------------------------------------------------------------------
# Application-specific features
# ---------------------------------------------------------------------------

def _write_application_features(
    buf: StringIO, result: DesignResult, plasmid_seq: str
) -> None:
    app = result.request.application
    insert = result.insert.upper()

    # Insert window: locate insert in plasmid
    insert_loc = _locate_subseq(plasmid_seq, insert)
    if insert_loc is not None:
        s, e, _ = insert_loc
        _write_feature(
            buf, "misc_feature", s, e,
            [
                ("label", f"insert ({len(insert)} bp)"),
                ("note", f"gene={result.gene_record.gene}; isolate={result.gene_record.isolate_id}"),
            ],
        )

    if app == "deletion":
        assert isinstance(result.primer_set, DeletionPrimerSet)
        scar = result.primer_set.scar_dna
        _annotate_orf(buf, plasmid_seq, scar, label="scar_ORF",
                      extra_note=f"length={len(scar)} bp")
    elif app == "tagging":
        assert isinstance(result.primer_set, TaggingPrimerSet)
        cassette = result.primer_set.cassette
        tag_name = result.primer_set.tag.name
        _annotate_orf(buf, plasmid_seq, cassette, label=f"{tag_name}_cassette",
                      extra_note=f"tag={tag_name}; length={len(cassette)} bp")
    elif app == "expression":
        assert isinstance(result.primer_set, ExpressionPrimerSet)
        cds = result.primer_set.coding_seq
        _annotate_orf(buf, plasmid_seq, cds, label="expressed_CDS",
                      extra_note=f"length={len(cds)} bp")


def _annotate_orf(
    buf: StringIO, plasmid_seq: str, orf: str, label: str, extra_note: str
) -> None:
    loc = _locate_subseq(plasmid_seq, orf.upper())
    if loc is None:
        return
    start, end, strand = loc
    _write_feature(
        buf, "CDS", start, end,
        [("label", label), ("note", extra_note)],
        strand=strand,
    )


def _locate_subseq(plasmid_seq: str, sub: str) -> tuple[int, int, str] | None:
    if not sub:
        return None
    fwd = find_all(plasmid_seq, sub)
    if fwd:
        return fwd[0] + 1, fwd[0] + len(sub), "+"
    rc = reverse_complement(sub)
    rev = find_all(plasmid_seq, rc)
    if rev:
        return rev[0] + 1, rev[0] + len(sub), "-"
    return None


def _write_enzyme_features(
    buf: StringIO, result: DesignResult, plasmid_seq: str
) -> None:
    """Annotate every occurrence of the chosen enzyme's recognition site."""
    from .config import RESTRICTION_SITES

    enz = result.request.enzyme
    site_info = RESTRICTION_SITES.get(enz)
    if site_info is None:
        return
    site = site_info[0]
    for s in find_all(plasmid_seq, site):
        _write_feature(
            buf, "misc_feature", s + 1, s + len(site),
            [
                ("label", f"{enz} site"),
                ("note", f"recognition={site}"),
            ],
        )
    # Sites on the reverse strand (palindromic enzymes will already match;
    # this catches asymmetric ones like ClaI ATCGAT — palindrome — most v1
    # enzymes are palindromes, but loop anyway for completeness).
    rc_site = reverse_complement(site)
    if rc_site != site:
        for s in find_all(plasmid_seq, rc_site):
            _write_feature(
                buf, "misc_feature", s + 1, s + len(site),
                [("label", f"{enz} site"), ("note", f"recognition={site} (RC)")],
                strand="-",
            )


# ---------------------------------------------------------------------------
# ORIGIN block
# ---------------------------------------------------------------------------

def _write_origin(buf: StringIO, sequence: str) -> None:
    buf.write("ORIGIN\n")
    seq = sequence.lower()
    for i in range(0, len(seq), 60):
        chunk = seq[i : i + 60]
        groups = " ".join(chunk[j : j + 10] for j in range(0, len(chunk), 10))
        buf.write(f"{i + 1:>9} {groups}\n")


# ---------------------------------------------------------------------------
# Helpers shared with fasta_writer
# ---------------------------------------------------------------------------

def _primers_in_order(result: DesignResult) -> list[Primer]:
    ps = result.primer_set
    if isinstance(ps, (DeletionPrimerSet, TaggingPrimerSet)):
        return [ps.p1, ps.p2, ps.p3, ps.p4]
    if isinstance(ps, ExpressionPrimerSet):
        return [ps.p1, ps.p2]
    raise TypeError(f"Unknown primer set type: {type(ps).__name__}")
